# -*- coding: utf-8 -*-
"""Flipped.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpvgLLtFj2k9ZRtVfV9BfYsw_cMcDW-t
"""

import numpy as np
from google.colab import drive
import math

drive.mount('/content/drive')

simulationFile = "resized_Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy"

def createDatasets(filename):
  fgrids = '/content/drive/MyDrive/ColabNotebooks/' + filename
  grids  = np.load(fgrids)#, mmap_mode='r')
  return grids

dataset = createDatasets(simulationFile)

# Perform vertical flip for each sub-array
flipped_vertical = np.array([np.flipud(sub_array) for sub_array in dataset])

# Perform horizontal flip for each sub-array
flipped_horizontal = np.array([np.fliplr(sub_array) for sub_array in dataset])

flipped_dataset = np.concatenate([dataset, flipped_horizontal], axis=0)#flipped_vertical], axis=0)

#np.where(np.all(dataset == np.fliplr(flipped_vertical[3])))
if np.where(np.all(dataset == np.fliplr(flipped_horizontal[3]), axis=(1,2)))[0][0] != 3:
  raise "No horizontal flip match"
if np.where(np.all(dataset == np.flipud(flipped_vertical[3]), axis=(1,2)))[0][0] != 3:
  raise "No vertical flip match"

flipped_dataset.shape

flipped_horizontal.shape

dataset.shape

np.save('/content/drive/MyDrive/ColabNotebooks/augmented_resized_Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy', flipped_dataset)

