# -*- coding: utf-8 -*-
"""Resize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K35bk56myOM-COxoo7fJfwGcGQb7QI0g
"""

import numpy as np
from google.colab import drive
import math

from skimage.transform import resize

drive.mount('/content/drive')

simulationFile = "Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy"

def createDatasets(filename):
  fgrids = '/content/drive/MyDrive/ColabNotebooks/' + filename
  grids  = np.load(fgrids)#, mmap_mode='r')
  return grids

dataset = createDatasets(simulationFile)

resized_dataset = resize(dataset, (15000, 64, 64))
resized_dataset2 = resize(dataset, (15000, 64, 64))

print(resized_dataset.shape)
print(dataset.shape)

np.array_equal(resized_dataset, resized_dataset2)

np.save('/content/drive/MyDrive/ColabNotebooks/resized64_Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy', resized_dataset)