# -*- coding: utf-8 -*-
"""ResizedVisualTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhdeaKqWCzkIsQ845zbO797QOMNLo_ew
"""

import numpy as np
from google.colab import drive
import math
import matplotlib.pyplot as plt

drive.mount('/content/drive')

simulationFile = "Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy"
resizedSimulationFile = "resized_Maps_Mtot_Nbody_SIMBA_LH_z=0.00.npy"

def createDatasets(filename):
  fgrids = '/content/drive/MyDrive/ColabNotebooks/' + filename
  grids  = np.load(fgrids)#, mmap_mode='r')
  return grids

dataset = createDatasets(simulationFile)
resizedDataset = createDatasets(resizedSimulationFile)

def preprocess_image(image):
  image = np.log(image)
  image /= np.max(image)
  return image

dataset = preprocess_image(dataset)
resizedDataset = preprocess_image(resizedDataset)

i = 200

plt.subplot(1, 2, 1)
plt.imshow(dataset[i], cmap='hot', interpolation='nearest')

plt.subplot(1, 2, 2)
plt.imshow(resizedDataset[i], cmap='hot', interpolation='nearest')

